name: platform_context
version: 0.2.1
description: Get the global platform context
dependencies:
  pub_semver: any
  collection: any
environment:
  sdk: '>=1.24.3 <2.0.0'
dev_dependencies:
  test: any
  dev_test: any
  browser: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
