name: platform_context
version: 0.1.1
description: Get the global platform context
dependencies:
dev_dependencies:
  test: any
  dev_test: any
  browser: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart