name: platform_context
version: 0.2.0
description: Get the global platform context
dependencies:
  pub_semver: any
  collection: any

dev_dependencies:
  test: any
  dev_test: any
  browser: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
